on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  ResourceGroup: letsencrypt-inttest
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2 
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI ARM deployment
      uses: azure/CLI@v1
      with:
        inlineScript: |
          cd internal/deploy
          az deployment group create --resource-group $ResourceGroup -f integration.json
